baseurl: "/Haal-Centraal-BAG-bevragen"
apiname: "BAG Bevragen"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt ge√∂pend.
nav:
  - title: BAG Bevragen
    subnav:
      - title: Main
        path: /
      - title: Goals canvas
        path: /goals-canvas
  - title: Specificaties v. 1.1 (Live)
    subnav:
      - title: Getting started
        path: /getting-started
      - title: User stories
        url: https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues?q=is%3Aopen+is%3Aclosed++is%3Aissue+label%3A%22user+story%22++label%3A%22v1.1%22+
        path: /user-stories
        target: blank
      - title: Bevragen API (swagger-ui)
        path: /swagger-ui
      - title: Bevragen API (redoc)
        path: /redoc
      - title: Features
        path: /features
#  - title: Specificaties v. 1.2 (IO)
#    subnav:
#      - title: User stories
#        url: https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues?q=is%3Aopen+is%3Aissue+label%3A%22user+story%22++label%3A%22v1.2%22+
#        path: /user-stories
#        target: blank
#      - title: Bevragen API (swagger-ui)
#        path: /swagger-ui-io
#      - title: Bevragen API (redoc)
#        path: /redoc-io
#      - title: Features
#        path: /features
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-haal-centraal

github: VNG-Realisatie/Haal-Centraal-BAG-bevragen

theme: jekyll-theme-time-machine

project_name: /Haal-Centraal-BAG-bevragen